menu:
	Blog: /
	Archive: /archives/
	Twitter: https://twitter.com/slavikshen
	GitHub: https://github.com/slavikshen
	Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-99998080-1

# Copyright Infomation
startyear: 2017
